### ISSUE TITLE
Can't Use Joker Commands

### ISSUE THREAD

**Issue by exassasinx** [Dnawrkshp/ArtemisPS3#8]
This worked for netcheat L1+Up activate codes but on artemis it doesn't? :/
D1 39EF061C 00101001
39EF061C 00101001
0 399F47E7 2D000000

**Comment by Dnawrkshp** [comment]
Artemis doesn't handle comments as good as NetCheat does. It looks like if you removed the middle line (or just moved it up or down) then it would start working. Try:
//39EF061C 00101001
D1 39EF061C 00101001
0 399F47E7 2D000000

**Comment by exassasinx** [comment]
Idk why but some of the codes that work for netcheat doesn't work for artemis

**Comment by exassasinx** [comment]
Like these
Infinite Health + Max Stats
0 009D1E18 3E00447A 
0 009D1E1C 92030008
0 009D1E20 92030014
0 009D1E24 3E204B18 
0 009D1E28 3E404B18
0 009D1E2C 9223004C
0 009D1E30 92230050
0 009D1E34 92230054
0 009D1E38 92230058
0 009D1E3C 9223005C
0 009D1E40 92430004
0 009D1E44 92430010
0 009D1E48 4875064A
0 00750644 489D1E1A

Invincible
0 00244CD8 4E800020

Infinite Jumps Hold R2
0 009D201C 3E00028E
0 009D2020 9090F044
0 009D2024 80840000
0 009D2028 487B231E
0 007B2318 489D201E
0 009D20A8 3E20028E
0 009D20AC 8231F044
0 009D20B0 60000000
0 009D20B4 72312000
0 009D20B8 60000000
0 009D20BC 2B912000
0 009D20C0 409E000C
0 009D20C4 60000000
0 009D20C8 935F0960
0 009D20CC 817F0924
0 009d20D0 482411F6
0 002411F0 489D20AA

**Comment by Dnawrkshp** [comment]
MAMBA fails to write to some memory (executable mostly). It's just a problem that probably will never be fixed. If you are on DEX and you still have this problem I don't know what to say. It should be writing.
Otherwise, either install CCAPI for your firmware or convert to a DEX firmware. The CCAPI option is much easier.
